### ISSUE TITLE
Undefined variable when a re-close a ticket

### ISSUE THREAD

**Issue by Albatros78** [pixeline/bugs#582]
Hello Patrick

Voilà ce que j'ai fait. 
J'avais 4 tickets fermés pour un projet.
J'ai réouvert les 4
J'ai changé le titre des tickets, et le referme le ticket en rajoutant un commentaire (pour pouvoir fermer l eticket)

et j'ai le message suivant: (mais le ticket est fermé !)

Unhandled Exception
Message:
Undefined variable: columns
Location:
E:\xampp\htdocs\bugtracker3\app\laravel\database\query\grammars\grammar.php on line 437
Stack Trace:
#0 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(40): Laravel\Error::native(8, 'Undefined varia...', 'E:\\xampp\\htdocs...', 437)
#1 E:\xampp\htdocs\bugtracker3\app\laravel\database\query\grammars\grammar.php(437): Laravel\{closure}(8, 'Undefined varia...', 'E:\\xampp\\htdocs...', 437, Array)
#2 E:\xampp\htdocs\bugtracker3\app\laravel\database\query.php(887): Laravel\Database\Query\Grammars\Grammar->update(Object(Laravel\Database\Query), Array)
#3 [internal function]: Laravel\Database\Query->update(Array)
#4 E:\xampp\htdocs\bugtracker3\app\laravel\database\eloquent\query.php(267): call_user_func_array(Array, Array)
#5 E:\xampp\htdocs\bugtracker3\app\laravel\database\eloquent\model.php(392): Laravel\Database\Eloquent\Query->__call('update', Array)
#6 E:\xampp\htdocs\bugtracker3\app\application\models\project\issue\comment.php(92): Laravel\Database\Eloquent\Model->save()
#7 E:\xampp\htdocs\bugtracker3\app\application\controllers\project\issue.php(81): Project\Issue\Comment::create_comment(Array, Object(Project), Object(Project\Issue))
#8 [internal function]: Project_Issue_Controller->post_index('2', '12')
#9 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#10 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('index', Array)
#11 E:\xampp\htdocs\bugtracker3\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('index', Array)
#12 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('project.issue@i...', Array)
#13 E:\xampp\htdocs\bugtracker3\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#14 E:\xampp\htdocs\bugtracker3\app\laravel\laravel.php(160): Laravel\Routing\Route->call()
#15 E:\xampp\htdocs\bugtracker3\index.php(19): require('E:\\xampp\\htdocs...')
#16 {main}

**Comment by Patriboom** [comment]
J'ai un problème avec mon PHP, je vous reviendrai prochainement.
